// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package queue

// CrazyNumberQueue is a queue of CrazyNumbers.
type CrazyNumberQueue struct {
	items []int
}

func NewCrazyNumberQueue() *CrazyNumberQueue {
	return &CrazyNumberQueue{items: make([]int, 0)}
}
func (q *CrazyNumberQueue) Push(item int) {
	q.items = append(q.items, item)
}
func (q *CrazyNumberQueue) Pop() int {
	item := q.items[0]
	q.items = q.items[1:]
	return item
}
